site_name: Consensus Experimentation on  the Climate-Change-Position-Statement
nav:
    - Home: index.md
    - Lesson 1: github.md
    - Lesson 2: jupyterhub.md
    - Lesson 3: conda.md
    - Lesson 4: earthdata.md
    - Lesson 5: numpy.md
    - Lesson 6: pandas.md
theme: 
    name: readthedocs
    highlightjs: true
plugins:
    - search
    - markdownextradata
extra:
  hackweek:
    name: Climate-Change-Position-Statement
    web_url: https://climatechangepoistion.github.io
    slack_url: https://waterhackweek.slack.com
    github_org_url: https://github.com/waterhackweek
    pangeo_url: https://aws-uswest2.pangeo.io
    admin_contact: Christina Bandaragoda
markdown_extensions:
  - admonition
repo_url: https://github.com/waterhackweek/Climate-Change-Position-Statement
